services:
  netin-web:
    container_name: netin-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://glados-server.13997906387.xyz
        VITE_GIPHY_API_KEY: ${VITE_GIPHY_API_KEY}
    restart: unless-stopped
    networks:
      - nginxnet

networks:
  nginxnet:
    external: true
